format_version: '2.0'
input_files: product-lines-minepump_spec1_product31_true-unreach-call_false-termination.cil-minepump_spec1_product31_true-unreach-call_false-termination.cil.-O0.smt2
options:
  language: SMT-LIB
properties:
- expected_verdict: true
  majority_vote_verdict: sat
  property_file: ../../properties/check-sat.prp
  sat:
  - eldarica
  - spacer
