format_version: '2.0'
input_files: product-lines-minepump_spec2_product04_true-unreach-call_false-termination.cil-minepump_spec2_product04_true-unreach-call_false-termination.cil.-O2.smt2
options:
  language: SMT-LIB
properties:
- expected_verdict: true
  property_file: ../../properties/check-sat.prp
# majority-vote verdict: true
# supporters (2): eldarica, spacer
