format_version: '2.0'
input_files: product-lines-email_spec0_product40_true-unreach-call_true-termination.cil-email_spec0_product40_true-unreach-call_true-termination.cil.-O2.smt2
options:
  language: SMT-LIB
properties:
- expected_verdict: true
  majority_vote_verdict: sat
  property_file: ../../properties/check-sat.prp
  sat:
  - eldarica
  - spacer
