format_version: '2.0'
input_files: product-lines-elevator_spec14_product24_false-unreach-call_true-termination.cil-elevator_spec14_product24_false-unreach-call_true-termination.cil.-O2.smt2
options:
  language: SMT-LIB
properties:
- expected_verdict: true
  property_file: ../../properties/check-sat.prp