format_version: '2.0'
input_files: product-lines-email_spec6_product34_false-unreach-call_true-termination.cil-email_spec6_product34_false-unreach-call_true-termination.cil.-O2.smt2
options:
  language: SMT-LIB
properties:
- expected_verdict: false
  majority_vote_verdict: unsat
  property_file: ../../properties/check-sat.prp
  unsat:
  - eldarica
